'''Problem 2
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 
 and 
, the first 
 terms will be:

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.'''

# Creating the Fibonacci sequence
fibonacci = [1, 2]
number_of_terms = 10
# Summing the last 2 terms in the list
for index in range(0, number_of_terms - 2):
    fibonacci.append(fibonacci[index + 1] + fibonacci[index])
# Showing the sequence
print(fibonacci)

# Using a funtion
def fibonachi(n):
    a,b=0,1
    while a<n:
        print(a,end=",")
        a,b = b, a+b
    print()

fibonachi(10)
  

